config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "list#index"

  get "index" => "list#index"
  get "painting" => "list#painting_index"
  get "work" => "list#work_index"

  get "mandara/:id" => "list#mandara_show"
  get "painting/:id" => "list#painting_show"
  get "work/:id" => "list#work_show"

  get "profile" => "list#profile"

  get "oracle" => "list#oracle"
  get "oracle_b" => "list#oracle_b"

  # 管理画面
  namespace :admin do
    root to: "oracle_cards#index"
    resources :oracle_cards
  end

  post "question_send" => "list#question_send"

  # 大宇宙インセンスの残骸
  #get "conference" => "list#conference"
  #get "conference_b" => "list#conference_b"
  #get "incense" => "list#incense"
  #get "incense_b" => "list#incense_b"
  #get "counseling" => "list#counseling"
  #get "counseling_b" => "list#counseling_b"
  #get "video" => "list#video"
  # 大宇宙インセンスご注文
  #get "order" => "list#order"
  #post "order_send" => "list#order_send"
  # お問い合わせ
  #get "question" => "list#question"

  # メール送信テスト用
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oracle_card.rb
class OracleCard < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :helper_description, presence: true
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  layout "admin"
end

app/controllers/admin/oracle_cards_controller.rb
class Admin::OracleCardsController < Admin::ApplicationController
  def index
    @oracle_cards = OracleCard.all.order(:title)
  end
  
  def new
    @oracle_card = OracleCard.new
  end
  
  def create
    @oracle_card = OracleCard.new(oracle_card_params)
    if @oracle_card.save
      redirect_to admin_root_path
    else
      render :new
    end
  end
  
  def edit
    @oracle_card = OracleCard.find(params[:id])
  end
  
  def update
    @oracle_card = OracleCard.find(params[:id])
    if @oracle_card.update(oracle_card_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    @oracle_card = OracleCard.find(params[:id])
    @oracle_card.destroy
    redirect_to admin_root_path
  end
  
  private

  def oracle_card_params
    params.require(:oracle_card).permit(:image, :title, :description, :helper_description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
    @imgs = [24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,]
    render template: "statics/index"
  end
  def painting_index
    @imgs2 = [12,11,10,9,8,7,6,5,4,3,2,1,]
    render template: "statics/painting"
  end
  def work_index
    @imgs3 = [15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,]
    render template: "statics/work"
  end
  
    #拡大画面
  def mandara_show
    @id = params[:id]
    render template: "statics/show1"
  end
  def painting_show
    @id = params[:id]
    render template: "statics/show2"
  end
  def work_show
    @id = params[:id]
    render template: "statics/show3"
  end

  def profile
    render template: "statics/profile"
  end
  
  def oracle
      render template: "card/oracle"
  end 

  # メールアドレスチェックの正規表現
  # https://qiita.com/shunhikita/items/772b81a1cc066e67930e  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # お問い合わせ送信
  def question_send
    @email = params[:email]
    @message = params[:message]

    @error_messages = []
    
    # エラー処理
    if not VALID_EMAIL_REGEX.match(@email)
      @error_messages << "メールアドレスが不正です。"
    end
    
    if @message.blank?
      @error_messages << "お問い合わせ内容を入力して下さい。"
    end

    if @error_messages.size > 0
      render template: "statics/profile"
      return
    end
    
    # メール送信
    QuestionMailer.send_question(@email, @message).deliver
    
    render template: "statics/question_send_complete"
  end 

  def oracle_b
    @oracle_card = OracleCard.offset(rand(OracleCard.count)).first
    render template: "card/oracle_b"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/cards/index.html.erb
<% content_for :title do %>
  カード一覧
<% end %>

<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
    </div>
    <div class="pull-right">
      <%= link_to new_admin_card_path, { class: "btn btn-default btn-sm" } do %>
        <i class="fa fa-plus"></i>
        新規作成
      <% end %>
    </div>
  </div>
  <div class="box-body table-responsive">
    <table class="table table-borderd table-hover">
      <thead>
        <tr>
          <th>ID
          <th>画像
          <th>説明
          <th>
        </tr>
      </thead>
    </table>
  </div>
</div>

app/views/admin/oracle_cards/_form.html.erb
<%= form_for([ :admin, oracle_card ], html: { class: "form-horizontal" }) do |f| %>
  <% if oracle_card.errors.any? %>
    <ul>
      <% oracle_card.errors.full_messages.each do |message| %>
        <li><%= message %>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :image, "", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, "", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_area :description, size: "100x15", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :helper_description, "", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_area :helper_description, size: "100x10", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
      <%= f.submit class: "btn btn-info btn-sm" %>
    </div>
  </div>
<% end %>

  

app/views/admin/oracle_cards/_oracle_card.html.erb
<tr>
  <td><%= oracle_card.id %></td>
  <td>
    <% if not oracle_card.image.file.nil? %>
      <%= image_tag oracle_card.image_url, width: "200" %>
    <% end %>
  </td>
  <td><%= oracle_card.title %></td>
  <td><%= oracle_card.description.truncate(200) %></td>
  <td><%= oracle_card.helper_description.truncate(200) %></td>
  <td class="text-right">
    <%= link_to "編集", edit_admin_oracle_card_path(oracle_card), class: "btn btn-default btn-sm" %>
    <%= link_to "削除", [ :admin, oracle_card ], method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-default btn-sm" %>
  </td>
</tr>

app/views/admin/oracle_cards/edit.html.erb
<% content_for :title do %>
  カード編集
<% end %>

<div class="box">
  <div class="box-header with-border">
  </div>
  <div class="box-body">
    <%= render 'form.html.erb', oracle_card: @oracle_card %>
  </div>
</div>

app/views/admin/oracle_cards/index.html.erb
<% content_for :title do %>
  カード一覧
<% end %>

<div class="box">
  <div class="box-header with-border">
    <div class="pull-left">
    </div>
    <div class="pull-right">
      <%= link_to new_admin_oracle_card_path, { class: "btn btn-default btn-sm" } do %>
        <i class="fa fa-plus"></i>
        新規作成
      <% end %>
    </div>
  </div>
  <div class="box-body table-responsive">
    <table class="table table-borderd table-hover">
      <thead>
        <tr>
          <th class="col-sm-1">ID</th>
          <th class="col-sm-2"><%= t("activerecord.attributes.oracle_card.image") %></th>
          <th class="col-sm-1"><%= t("activerecord.attributes.oracle_card.title") %></th>
          <th class="col-sm-3"><%= t("activerecord.attributes.oracle_card.description") %></th>
          <th class="col-sm-3"><%= t("activerecord.attributes.oracle_card.helper_description") %></th>
          <th class="col-sm-2"></th>
        </tr>
      </thead>

      <%= render @oracle_cards %>
    </table>
  </div>
</div>

app/views/admin/oracle_cards/new.html.erb
<% content_for :title do %>
  カード登録
<% end %>

<div class="box">
  <div class="box-header with-border">
  </div>
  <div class="box-body">
    <%= render 'form.html.erb', oracle_card: @oracle_card %>
  </div>
</div>

app/views/card/anxiety.html.erb
<h1>【不安】</h1>
<p>
不安。不安と言う感情は、五大感情（楽しみ・嫌気・悲しみ・恐れ・怒り）の恐れの中にあるパーツの一つです。

このカードを引いたあなたは、訪れるかもしれない脅威への不安を感じていたり、又は周りで不安を感じていたりする人の影響を受けていたりするのではないでしょうか？

健康面での不安、仕事における不安、人間関係、将来の展望、金銭面、異性関係、それらの不安に苛まれている時、手立ての打ちようが無い無力感や、それを回避しようと過剰になって取越し苦労をしていませんか？

不安を感じている時は、消極的になっていたりネガティブに物事を考えやすくもなります。イライラとしたり怒りっぽくもなります。不安は、逃避や攻撃の対象として捉えられる事がよくあります。

暴飲暴食、ギャンブルやsexなどその場しのぎの興奮を求めてみたり、心の隙間に入り込む悪徳ビジネスや、カルト宗教、不安をあおる自己啓発セミナー、更には身を滅ぼすドラッグの使用。これらは、全て【不安】からくる逃避行動とも考えられます。

不安は、恐れのハウスの中で展開しています。逆に恐れの中でしか生きられない性質を持っています。

人間は、大事にしている事、大切な人や物、そう言った風に思う事が出来てくると必然的にそれを失うかもしれない。と言う脅威への不安が出てきます。

しかし、冷静に考えてみると、それは皆んな一緒の事。不安を感じない人間なんて存在しないでしょう。

では、解決策がなくただ呆然と、この不安と言う感情を雨雲が通り過ぎるのを待つかのように暗い気持ちでひたすら待つしかないのでしょうか？

このカードがあなたに、伝えたいメッセージは、《目を見開いて今の現実に適切に向き合う事》を示しています。

適切に向き合う事は、正しく物事を見る事でもあります。

不安があるから、準備や備えができる。
不安があるから、他者に協力を求める事ができる
不安があるから、同じような不安を持つ人の気持ちを理解する事できる。

不安があるから、修正、改善する事ができる。
不安があるから、傲慢、慢心にならずにいられる。

と、このように不安を正しく見ていくと、その奥（裏側）には、恩恵があります。

適切に不安と向き合う事で、それは脅威だけでは無い事が見えてきます。

そうしていく内に、恐怖のハウスの中に自ら入っていた事に気づいていきます。家や教室と言う空間では、決まり事や固定観念が支配しやすい性質があります。そういった場にいるとなかなか物事を自分の目で正しく観る事が難しくなってきます。

それは、物理的にも心理的にも言わばフレームの中に閉じ込められた状態と言ってもいいでしょう。

もし、不安を感じてしまっている場合、今自分は、恐怖や不安と言うフレームの中に入ってしまっていないか？と確認して行く事も有効かもしれません。（reframing！）

あなたが、恐怖や、不安から抜け出し輝いて生きる事を皆んなが待っている事でしょう</p>

<h1>【Helper】助っ人</h1>
<p>そんな、不安を感じている時に手助けしてくれるのが、聖なる植物のエッセンスです。このカードで助っ人の役目を果たしてくれるのが、《ラベンダー》です。ラベンダーは、心を鎮めて落ち着かさせてくれる、多面性を持つエッセンスです。あらゆる種類の問題に効き目を発揮します。宗教的な部分でも伝統的に使われてきた植物でもあります。

今日でも教会の香の調合として使われています。

気持ちを、リラックスさせゆるやかに浄化の方向に導き、つながりを作る穏やかな刺激も秘めています</p>

app/views/card/oracle.html.erb
<% content_for :menu_setting do %>
  <% @menu = :oracle %>
<% end %>

<section class="container">
<div class="row box1">
<div class="col-sm-4 bgme box2">
<a href="oracle_b"><img src="img/cord5_ura.png" class="card-img-top" alt="カード画像"></a>
</div>

<div class="col-sm-8 bg box2">
<h5 class="mt-0">数秘術占い</h5>

<p>自主制作した占いゲームです、天使たちは私たちに何かのメッセージを常に<br>
送り続けています一番伝わりやすいのが数字電話番号や車のナンバーなど<br>
最近よく見かけるという番号はありませんか？それはもしかしたら天使たち<br>
からのメッセージかもしれませんよ、ここではその数字で占って行きます</p>
<br>
<br>
<br>
<p>まずは心を充分に静めてからカードをクリックしてください</p>

</div>
</div>

</section>


app/views/card/oracle_b.html.erb
<% content_for :menu_setting do %>
  <% @menu = :oracle %>
<% end %>

<section class="container">
<div class="row box1">
<div class="col-sm-4 bgme box2">
  <%= image_tag @oracle_card.image_url, class: "card-img-top" %>
</div>

<div class="col-sm-7 bg box2">
<h4 class="mt-0">【<%= @oracle_card.title %>】</h4>

<p>
  <%= @oracle_card.description.html_safe %>
</p>

<h5>●●--この数字の意味--●●</h5>

<p>
  <%= @oracle_card.helper_description&.html_safe %>
</p>

</div>
<div class="col-sm-1 bg box2">
</div>
</div>
</section>


app/views/layouts/_admin_footer.html.erb
<!-- To the right -->
<div class="pull-right hidden-xs">
</div>
<!-- Default to the left -->
<strong>Copyright &copy; 2018-2021 <a href="/">曼荼羅アートギャラリー「ひとつ」</a>.</strong> All rights reserved.

app/views/layouts/_admin_header.html.erb
<%= link_to admin_root_path, { class: "logo" } do %>
  <span class="logo-mini"></span>
  <span class="logo-lg">管理画面</span>
<% end %>

<!-- Header Navbar -->
<nav class="navbar navbar-static-top" role="navigation">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>
  <!-- Navbar Right Menu -->
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">

      <!-- Tasks Menu -->
      <li class="dropdown tasks-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <!--
          <i class="fa fa-flag-o"></i>
          <span class="label label-danger"></span>
          -->
        </a>
        <ul class="dropdown-menu">
        </ul>
      </li>

      <!-- User Account Menu -->
      <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <!-- The user image in the navbar-->
          <!--<img src="https://almsaeedstudio.com/themes/AdminLTE/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
          <!-- hidden-xs hides the username on small devices so only the image appears. -->
          <span class="hidden-xs"></span>
        </a>
        <ul class="dropdown-menu">
        </ul>
      </li>

      <li>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_admin_sidebar.html.erb
<!-- Sidebar Menu -->
<ul class="sidebar-menu" data-widget="tree">
  <li class="header">メイン</li>
  <!-- Optionally, you can add icons to the links -->
  <% if request.path_info == admin_oracle_cards_path %>
    <li class="active">
  <% else %>
    <li>
  <% end %>
    <%= link_to admin_oracle_cards_path do %>
      <i class="fa fa-link"></i> <span>カード一覧</span>
    <% end %>
  </li>
  <!--
  <li class="treeview">
    <a href="#"><i class="fa fa-link"></i> <span>設定</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li>
        <%#= link_to admin_admin_users_path do %>
          管理ユーザー
        <%# end %>
      </li>
    </ul>
  </li>
  -->
</ul>
<!-- /.sidebar-menu -->

app/views/layouts/_menu.html.erb
<% yield :menu_setting %>

<div class="row py-2 box1">
  <div class="col">
    <% class_non_active = "btn btn-info box5" %>
    <% class_active = "btn btn-info box5 active" %>

    <% [
         [ "曼荼羅", "/index", :index ],
         [ "曼荼羅塗り絵", "/painting", :painting ],
         [ "他の作品", "/work", :work ],
         [ "占い", "/oracle", :oracle ],
         [ "自己紹介", "/profile", :profile ],
       ].each do |menu| %>
    
      <%= link_to menu[0], menu[1], class: @menu == menu[2] ? class_active : class_non_active %>
    <% end %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <title>
    <%= content_for(:title) ? yield(:title) + " | " : "" %>管理画面
  </title>

  <!-- Bootstrap -->
  <!-- https://getbootstrap.com/docs/3.3/getting-started/ -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Font Awesome -->
  <!-- https://www.bootstrapcdn.com/fontawesome/ -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Ionicons -->
  <!-- http://ionicons.com/#cdn -->
  <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/css/AdminLTE.min.css">
  <!-- AdminLTE Skins -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/css/skins/_all-skins.min.css">
  <%#= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Favicon -->
  <link rel="shortcut icon" href="/images/favicon.ico" />

  <%= csrf_meta_tags %>
</head>

<!-- Based on https://adminlte.io/themes/AdminLTE/starter.html -->
<body class="hold-transition skin-green sidebar-mini fixed">
  <div class="wrapper">

    <!-- Main Header -->
    <header class="main-header">
      <%= render "layouts/admin_header" %>
    </header>

    <aside class="main-sidebar">
      <%= render "layouts/admin_sidebar" %>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <section class="content-header">
        <h3><%= yield(:title) %></h3>
      </section>
      <section class="content container-fluid">
        <%= content_for(:content) ? yield(:content) : yield %>
      </section>
    </div><!-- .content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <%= render "layouts/admin_footer" %>
    </footer>

  </div><!-- .wrapper -->

  <!-- jQuery -->
  <!-- https://code.jquery.com/ -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <!-- Bootstrap -->
  <!-- https://getbootstrap.com/docs/3.3/getting-started/ -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.2/js/adminlte.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= yield :js %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="keywords" content="曼荼羅アートギャラリーひとつ">
  <meta name="description" content="曼荼羅アートギャラリー「ひとつ」で創作した曼荼羅に触れて貰い曼荼羅の魅力を再発見する為のサイトです、オリジナル曼荼羅や塗り絵、曼荼羅を使用したアート作品を紹介したり、占いゲームなどをプレイしてもらいます">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>曼荼羅アートギャラリー「ひとつ」</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/base.css">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47471078-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-47471078-2');
</script>
<style>
    .box1{
        background-color: rgb(206, 233, 165);
    }
    .box2{
        background-color: rgb(187, 238, 167);
        align-items: start;   
    }
    .box3{
      background-color: rgb(128, 245, 208);
    }
    .box4{
      background-color: rgb(190, 226, 235);
    }
    .box5{
      background-color: rgb(171, 240, 164);
    }
</style>
</head>

<body class="box4">
  <% if @no_header != true %>
  <header class="container box1">
    <div class="row">
      <div class="col">
        <div class="headr-title">
          <img src="/img/top.jpg" class="img-fluid mt-2 rounded" alt="Responsive image">
        </div>
      </div>
    </div>
    <%= render "layouts/menu" %>
  </header>
  <% end %>

  <%= yield %>
  
  <footer class="container box1">
    <%= render "layouts/menu" %>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</body>
</html>

app/views/statics/index.html.erb
<% content_for :menu_setting do %>
  <% @menu = :index %>
<% end %>

<div class="container">
  <div class="row box1">
    <% @imgs.each do |i| %>
      <div class="col-md-sm-3 card mt-1 ml-1 box2" style="width: 280px;">
        <img src="img/mandara/<%= i %>.jpg" class="img-fluid shadow rounded mt-2 ml-2 mr-2" style="width: 265px; alt="...">
        <div class="card-body">
          <h6 class="card-title">曼荼羅ナンバー<%= i %></h6>
          <a href="/mandara/<%= i %>.html" class="btn btn-info box3">拡大画面</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/statics/painting.html.erb
<% content_for :menu_setting do %>
  <% @menu = :painting %>
<% end %>

<div class="container">
  <div class="row box1">
    <% @imgs2.each do |i| %>
      <div class="col-md-sm-3 box2 card mt-1 ml-1" style="width: 280px;">
        <img src="/img/painting/<%= i %>.jpg" class="img-fluid shadow rounded mt-2 ml-2 mr-2" style="width: 265px; alt="...">
        <div class="card-body">
          <h6 class="card-title">塗り絵ナンバー<%= i %></h6>
          <a href="/painting/<%= i %>" class="btn btn-info box3">拡大画面</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/statics/question_send_complete.html.erb
<% content_for :menu_setting do %>
  <% @menu = :profile %>
<% end %>

<section class="container">
  <div class="row box1">
    <div class="col bgf box2">
      <h1 class="mt-3">送信完了</h1>

      <p>
        お問い合わせを受け付けました。<br>
        数日以内にご入力いただいたメールアドレス宛に返信させていただきます。<br>
        1 週間以上返信がない場合はメールアドレスを間違えている可能性がありますので、
        再度こちらよりお問い合わせしていただけますと幸いです。
      </p>
    </div>
  </div>
</section>

app/views/statics/show1.html.erb
<% content_for :menu_setting do %>
  <% @menu = :index %>
<% end %>

<div class="container box1">
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
      <img src="/img/mandara/<%= @id %>.jpg" class="img-fluid rounded shadow mt-1 mb-3">
      <div>
        <a href="/index" class="btn btn-info box3 mt-3">Go 戻る</a>
        <a href="/mandara/<%= @id.to_i - 1 %>" class="btn btn-info box3 mt-3">Go 次へ</a>
      </div>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>

app/views/statics/show2.html.erb
<% content_for :menu_setting do %>
  <% @menu = :painting %>
<% end %>

<div class="container box1">
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-8">
      <img src="/img/painting/<%= @id %>.jpg" class="img-fluid rounded shadow mt-1 mb-3">
    　<div>
        <a href="/painting" class="btn btn-info box3 mt-3">Go 戻る</a>
        <a href="/painting/<%= @id.to_i - 1 %>" class="btn btn-info box3 mt-3">Go 次へ</a>
    　</div>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>